[package]
name = "bt_core_config"
version = "0.2.10"
edition = "2024"
authors = ["calvarez <calvarez@bachuetech.biz>"]
description = "Core Configuration. Application and Server."

[dependencies]
bt_logger = "0.3.1"
bt_yaml_utils = "0.1.14"
yaml-rust2 = "0.11.0"
